name: Destroy Infra and App on GCP

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: ${{ vars.GCP_REGION }}
  SERVICE_NAME: ${{ vars.GCP_SERVICE_NAME }}
  FRONTEND_DIR: ${{ vars.FRONTEND_DIR }}
  TF_DIR: ${{ vars.TF_DIR }}

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="project_id=${{ env.PROJECT_ID }}"

  cleanup-cloud-run:
    needs: terraform-destroy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Delete Cloud Run service
        run: |
          if gcloud run services describe $SERVICE_NAME --region $REGION > /dev/null 2>&1; then
            gcloud run services delete $SERVICE_NAME --region $REGION --quiet
          else
            echo "Cloud Run service $SERVICE_NAME no existe, saltando..."
          fi

      - name: Delete Artifact Registry images
        run: |
          gcloud artifacts docker images delete ${REGION}-docker.pkg.dev/$PROJECT_ID/hackday-repo/$SERVICE_NAME:latest \
            --quiet --delete-tags || echo "No image found to delete"

  cleanup-firebase:
    needs: terraform-destroy
    runs-on: ubuntu-latest
    steps:
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Validate Firebase Token
        run: |
          firebase list --token "${{ secrets.FIREBASE_TOKEN }}" || (echo "❌ Token inválido o caducado" && exit 1)

      - name: Disable Firebase Hosting deployment
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          firebase hosting:disable --token ${{ secrets.FIREBASE_TOKEN }} || echo "No hosting to disable"
