name: Run Makefile on PR to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed  # incluye merge

jobs:
  run-make:
    if: github.event.pull_request.merged == true || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Make
        run: sudo apt-get install -y make
<<<<<<< HEAD
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
=======
>>>>>>> e43e1194718c748c7abcbace9e38cabb8f78d4da

      - name: Run setup-data
        run: make setup-data
